const byId = (id) => document.getElementById(id); let settings = null;
function request(message) { return new Promise((resolve, reject) => { chrome.runtime.sendMessage(message, (response) => { if (chrome.runtime.lastError) return reject(new Error(chrome.runtime.lastError.message)); if (!response?.ok) return reject(new Error(response?.error || "Unable to update Crypsis.")); resolve(response.data); }); }); }
function setMessage(value = "") { byId("message").textContent = value; }
function listItem(domain, removeType) { const item = document.createElement("li"); const label = document.createElement("span"); label.textContent = domain; const button = document.createElement("button"); button.type = "button"; button.textContent = "Remove"; button.addEventListener("click", async () => { try { settings = removeType === "custom" ? await request({ type: "removeCustomDomain", domain }) : await request({ type: "setSitePaused", hostname: domain, paused: false }); render(); } catch (error) { setMessage(error.message); } }); item.append(label, button); return item; }
function render() { byId("globalToggle").checked = settings.enabled; byId("cosmeticToggle").checked = settings.cosmeticFiltering; const custom = byId("customList"); custom.replaceChildren(...settings.customDomains.map((domain) => listItem(domain, "custom"))); const allowed = byId("allowedList"); allowed.replaceChildren(...settings.allowedSites.map((domain) => listItem(domain, "allowed"))); byId("allowEmpty").hidden = settings.allowedSites.length > 0; byId("clearAllowed").disabled = settings.allowedSites.length === 0; }
async function load() { settings = await request({ type: "getState" }); render(); }
byId("globalToggle").addEventListener("change", async (event) => { try { settings = await request({ type: "setEnabled", enabled: event.target.checked }); render(); } catch (error) { setMessage(error.message); } });
byId("cosmeticToggle").addEventListener("change", async (event) => { try { settings = await request({ type: "setCosmeticFiltering", enabled: event.target.checked }); render(); } catch (error) { setMessage(error.message); } });
byId("customForm").addEventListener("submit", async (event) => { event.preventDefault(); try { settings = await request({ type: "addCustomDomain", domain: byId("customDomain").value }); byId("customDomain").value = ""; setMessage("Custom filter added."); render(); } catch (error) { setMessage(error.message); } });
byId("clearAllowed").addEventListener("click", async () => { try { settings = await request({ type: "clearAllowedSites" }); render(); } catch (error) { setMessage(error.message); } });
load().catch((error) => setMessage(error.message));
